### ISSUE TITLE
Why is the disk-journal split over two files?

### ISSUE THREAD

**Issue by klr8** [bitronix/btm#70]
The DiskJournal writes to two parts configured using bitronix.tm.journal.disk.logPart1Filename and bitronix.tm.journal.disk.logPart2Filename.

Why is this?
Should you configure these parts to reside on different physical disks?
Should these disks be local disks and not network mounts?

I can't seem to find any recommendations about this in the documentation.
Maybe I missed something?

**Comment by lorban** [comment]
The DiskJournal is loosely based on Mike Spille's proposal, see http://jroller.com/pyrasun/entry/xa_exposed_part_iii_the under 'The TM Transaction Log' paragraph for reference.

In a nutshell, the DiskJournal is a simple append-only journal. It writes transaction logs to one of the two files (the one elected as the 'active' when the journal is opened) then when that file is full, it copies the logs of the unterminated transactions to the second file (i.e.: a simple way of compacting) and resume logging on to the latter. This simple two preallocated files strategy prevents a lot of problems like having to handle disk full conditions for instance.

Only one file is used at a time, but both files form the journal and should be backed up together. They can be put on different disks but that doesn't help performance so I would recommend to keep them colocated. I would not recommend network mounts as BTM would grind to a halt if the journal was to become unwritable, and since every single transaction commit ends up sync'ing the write to the physical disk, performance could suffer.

You're not missing much, I chose that mechanism for its simplicity and total lack of maintenance requirement and complex partitioning, hence also eliminating the need for a long documentation. Just put your files on a fast local disk and back them up along your DB and you should be good.

**Comment by klr8** [comment]
Thanks for the insights Ludovic!
Now at least I know I'm not doing anything stupid. :-)
As always, much appreciated!
