### ISSUE TITLE
searching best solution for error handling

### ISSUE THREAD

**Issue by testeradam** [bitronix/btm#84]
Using BTM as distributed transaction manager, How can this scenario be well handled. after reading a message from Active MQ  My transaction starts and I perform two database operation and any unexpected exception happens the Database operations are rolled back and the message is sent to Dead Letter Queue in Active Mq where I can re-process my message again. but there is one scenario after doing 1st database operation. while doing second database transaction if there is any data validation like null values how can I 
rollback the database transaction alone and send a message to the different queue? not Dead Letter Queue.

**Comment by lorban** [comment]
I can't say much with so few details. By default, ActiveMQ does not send rolled back messages to the DLQ, but it redelivers them. Have you changed that default, or are you speaking about multiple rolled back redeliveries?

You usage of the word "transaction" is a bit confusing too:
> after reading a message from Active MQ My transaction starts
What transaction? If you're speaking about a JTA transaction that encompasses your JMS and JDBC resources, it has to be started before you read the JMS message.
> ...while doing second database transaction...
Again, a confusing use of the word transaction.

Since you seem to be having architectural / design questions, nothing related to BTM itself, you should probably seek for help somewhere else.
